# Configuration for train.py


# Set global seed
set_seed: 42

# Set number of workers (int | float)
num_workers: 0.6

# Config dataset
data:
  data_path: vrpc/data/rpc-classify_x
  augment_level: 0
  image_size: [672, 672]
  data_limit: 0.1

# Config model
model:
  pretrained: false
  freeze: false

# Config scheduler
scheduler:
  warmup_epochs: 3
  start_factor: 0.01

# Config trainer
trainer:
  batch_size: 32
  learning_rate: 1e-3
  num_epoch: 10
  checkpoint: null
  precision: 32
