# Configuration for train.py


# Set global seed
set_seed: 42

# Set number of workers (int | float)
num_workers: 0.6

# Config dataset
data:
  data_path: vrpc/data/tiny-imagenet-200
  augment_level: 0
  image_size: [64, 64]
  data_limit: null

# Config model
model:
  pretrained: false
  freeze: false

# Config scheduler
scheduler:
  warmup_epochs: 5
  start_factor: 0.01

# Config trainer
trainer:
  batch_size: 128
  learning_rate: 1e-3
  num_epoch: 20
  checkpoint: null
  precision: 16-mixed
